### ISSUE TITLE
Run Taquito integration tests against "mondaynet" every week.

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#1102]
The goal is to discover failing Taquito tests against future Tezos protocols earlier. 

**Describe the solution you'd like**

I would like the Taquito integration tests  to run against the `mondaynet` testnet every Tuesday ("Testing Tuesday") so that we surface failing tests against future protocols earlier on in the protocol development lifecycle. 

**Describe alternatives you've considered**

Alternatives; Give someone the responsibility to manually run Taquito integration tests against mondaynet every week. 

**Additional context**

Mondaynets are launched by automatic schedule on every Monday. See project webpage here: https://teztnets.xyz/

**Comment by Innkst** [comment]
Need to setup keygen service for mondaynet

**Comment by michaelkernaghan** [comment]
this is up and running and has found results. closing the issue.

**Comment by danielelisi** [comment]
Reopening this Issue since #1440 hasn't been merged yet. The known smart contracts are required for the Taquito integration tests to run correctly. Since `mondaynet` is reset every week the pipeline deploys  the required contracts before each Integration test run; however, we're facing issues deploying the Sapling smart contract on the current `alpha` protocol (future J protocol)
