### ISSUE TITLE
Better way of dealing with Counter error

### ISSUE THREAD

**Issue by carte7000** [ecadlabs/taquito#164]
When your operation timeout it is not possible to broadcast another transaction with the same counter

- If the network is stuck you have to wait for your transaction to be included in a block
- If your fees are too low you can have to wait for a long time before your transaction get included

At the moment it is unclear how to handle this situation with Taquito. The current behavior of Taquito is to fetch the last counter from the network which could be a duplicate of a pending transaction and lead to an error from the RPC

```
[
  {
    "kind": "temporary",
    "id": "failure",
    "msg": "Error while applying operation opM9eB8HHyKKDsihnFbpxH4J4mrnQVAvtThnNyXucjbEbSK1NUp:\nbranch refused (Error:\n                  Counter 20504 already used for contract tz1S81cNZFSUwvzJZZdg7hzF8eJ9EgreVEfh (expected 20505)\n)"
  }
]
```

**Comment by jevonearth** [comment]
Consider removing the default timeout on `op.confirmation()` during this work. Make the default infinity.

@oleiba ran into this issue.

**Comment by oleiba** [comment]
@carte7000, is this error reproduced when increasing the fee?
If so, is that an error that originates from node? Having an RPC error hints that it is.
If that error originates from the node, I wonder - is it possible at all to "replace by fee" with Tezos default node implementation, as possible with Ethereum? 
Otherwise, it is definitely desired to be supported in taquito because that's a common pattern.

**Comment by carte7000** [comment]
@oleiba AFAIU this is reproduced when increasing the fees, preventing us from doing a `replace by fee` like in Ethereum. Changing the target node might work if the old transaction is not already in it's mempool. I need to have a closer look to this issue to see what are the possibilities.

Any idea that you see might fit here is more than welcome.

**Comment by oleiba** [comment]
Yeah, you might change the target node altogether (including for the first transaction) as this behaviour is not enforced by consensus, so there might be some deviation between different implementations or configurations of a node (long shot, but I assume it is really easy to test). 

If that doesn't work, I think it's worth opening an issue on Tezos node implementation since this is a big missing feature IMO

**Comment by carte7000** [comment]
We opened a new issue in the Tezos node, https://gitlab.com/tezos/tezos/issues/644

Feel free to suggest edit or comment

**Comment by carte7000** [comment]
For reference https://tezos.stackexchange.com/questions/1856/operation-injected-to-node-but-not-added-to-blockchain-wallet-counter-error

**Comment by michaelkernaghan** [comment]
1. the issued logged on tezos has been closed and fixed
2. this concerns emmy, which was replaced in Ithaca by Tenderbake
