### ISSUE TITLE
integration tests setup: bigmap known contract origination failing in MondayNet

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taquito#1701]
**Description**
In Taquito running against mondaynet, the integration test setup fails to originate the know bigmap contract.
However, the contract can be created on mondaynet in tezos-client

In taquito the orignation is fine on ithacanet and jakrtanet.
In the mondaynet upgrade of the week of 10 june 2022 the origination on mondaynet broke.
the git status for the mondaynet this issue was found in was "HEAD detached at a5e3e96fd"

**Steps To Reproduce**
the mondaynet pipeline is failing to deploy one of the known contracts:
> integration-tests@13.0.0 test:originate-known-contracts
> MONDAYNET=true node -r ts-node/register originate-known-contracts.ts
knownContract address:  KT1Qz9LTZcUFCrE9byz2fkHW2oJENAnuTuaG
Failed to deploy BigMapContract known contract | Error: HttpResponse: Http error response: (404) 
    at HttpBackend.<anonymous> (/home/runner/work/taquito/taquito/packages/taquito-http-utils/dist/taquito-http-utils.umd.js:474:31)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/taquito/taquito/packages/taquito-http-utils/dist/taquito-http-utils.umd.js:30:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
knownTzip12BigMapOffChainContract address:  KT1UXza7vbby7TpybrNCNAAVsQc8hrDkpdsT
knownSaplingContract address:  KT1JQ9coPM1FXVvrUzkta6BkqRhaLrGuEZEA
################################################################################
Public Key Hash : tz2PNzx3yhQLMs4k1gA46YKcbue1Dgt8ff1M
Initial Balance : 10 XTZ
Final Balance   : 8.216972 XTZ
Total XTZ Spent : 1.783028 XTZ

Here is the instruction to originate the contract on mondaynet with tezos-client:
```
tezos-client originate contract bigmapContract2 transferring 0 from gad0 running bigmapContract.tz --init 'Pair (Pair {Elt "tz1WjVVto6somKvasx8sWUn4JeQQMRhtNi6m" (Pair {Elt "tz1WjVVto6somKvasx8sWUn4JeQQMRhtNi6m" 1} 1)} "tz1gvF4cD2dDtqitL3ZTraggSR1Mju2BKFEM") True 100' --burn-cap 2 --gas-limit 200_000
```

**Comment by michaelkernaghan** [comment]
Here are the outputs from running the origination request on jakartanet versus o mondaynet.  You can search the mondaynet.out file for 404 to see where the failure was and compare it to jakartanet.out to see the difference and isolate which call fails on mondaynet.

**Comment by michaelkernaghan** [comment]
another view of the error, this time from running example:  ~/taquito/example/deploy-docs-live-code-contracts.ts
```
err :Error: Request failed with status code 404
errorData :
HttpResponse: Http error response: (404) 
    at HttpBackend.<anonymous> (/home/mike/taquito/packages/taquito-http-utils/src/taquito-http-utils.ts:147:6)
    at Generator.throw (<anonymous>)
    at rejected (/home/mike/taquito/packages/taquito-http-utils/dist/taquito-http-utils.umd.js:30:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 404,
  statusText: 'Not Found',
  body: '',
  url: 'http://mondaynet.ecadinfra.com:8732/chains/main/blocks/head/context/contracts/KT1KLT5jHrKPHcb8opGKgNRxpHNMWeuA29yR'
}
```
This is the same error but from a different contract origination test,

**Comment by michaelkernaghan** [comment]
I was able to originate on mondaynet with Taquito all of the contracts used in Taquito I've code examples in docseExcept for the contract called "BigMapsMultipleValuesContract".

on Ithaca this contract is here:  https://better-call.dev/ithacanet/KT1MMfuLrpBufDyxrLFkxBNE73Lp3AWkHivG/code

also on ithaca, the other failing origination mentioned above, called "KnownBigMapCOntract" is here:

https://better-call.dev/ithacanet/KT1JmL7j8CY371kRF2oZoJmzi7EUWbLPjEqZ/code

**Comment by roxaneletourneau** [comment]
I try deploying the "KnownBigMapContract", but it fails because the gas_limit set by the estimate is too low "proto.alpha.gas_exhausted.operation".
The `consumed_milligas` returned when doing the simulation `helpers/scripts/run_operation` is 3957526. However, the real consumed milligas seems to be 4066506. It seems that the consumed_milligas returned by `helpers/scripts/run_operation` is too low.

**Comment by michaelkernaghan** [comment]
Here are the results on MOndaynet of some of the contract origination with Bigmaps tests, to show which ar affected by this problem and which are not:

**Comment by roxaneletourneau** [comment]
The issue is the same for `~/taquito/integration-tests/data/tokens.ts`. The consumed_milligas returned by `/helpers/scripts/run_operation` and `/helpers/preapply/operations` is too low. Thus, the auto estimate of Taquito is not working properly: The `consumed_milligas` returned by the RPC is 3736504, Taquito set the gas_limit to 3837 (3736504/1000+100), the operation fails with "proto.alpha.gas_exhausted.operation".

Failure with gas auto-estimation:
![image](https://user-images.githubusercontent.com/65877347/174688881-e3bb1f26-aad5-430c-9fd1-f3057a3d723a.png)
Success if manually specify the gas_limit:
![image](https://user-images.githubusercontent.com/65877347/174689005-269448b1-bc55-465d-91ac-61f088483599.png)

**Comment by michaelkernaghan** [comment]
This is fixed now and tests are working again. Closing.
