### ISSUE TITLE
@taquito/beacon-wallet 13.0.1 - libsodium issue

### ISSUE THREAD

**Issue by boz1** [ecadlabs/taquito#1761]
**Description**
I've added ghostnet support to [tzprofiles](https://github.com/spruceid/tzprofiles). To do so, I updated taquito dependencies to 13.0.1, which in return caused libsodium errors. Fixed it eventually by deleting the node_modules in @taquito/beacon-wallet and re-installing them. The original PR to tzprofiles can be found [here](https://github.com/spruceid/tzprofiles/pull/190).

**Steps To Reproduce**
1. Clone https://github.com/spruceid/tzprofiles
2. Go to dapp directory
3. Run `npm install`
4. Update taquito dependencies to latest version
5. Run dapp with `npm run dev`
6. Go to localhost:9080
7. Open browser console
8. See `Cannot read properties of undefined (reading 'rc')` error

**Expected behavior**
Updating the taquito dependencies shouldn't cause a libsodium issue

**Desktop**
 - macOS (12.4)
 - chrome (Version 103.0.5060.114)

**Screenshot**
<img width="1435" alt="Screenshot 2022-07-22 at 12 20 16" src="https://user-images.githubusercontent.com/15712844/180419280-9e23faa8-3582-417e-a278-a92c2aa88384.png">

**Comment by claudebarde** [comment]
It looks like the issue comes from a stale version of Taquito in the node modules that is solved by deleting them and reinstalling them. It may be possible that the first update didn't overwrite some files, which caused the issue.
If you delete all the node modules, reinstall everything and it works, that doesn't look like a bug from Taquito.
