### ISSUE TITLE
QUESTION: Risks of using In Memory Signer in production

### ISSUE THREAD

**Issue by vnea** [ecadlabs/taquito#1764]
Hello,

In the [In Memory Signer documentation](https://tezostaquito.io/docs/inmemory_signer), it is said :
>WARNING
Storing private keys in memory is suitable for development workflows **but risky for production use-cases**!

What are the risks ?
Can you provide more details please ?

**Comment by zainen** [comment]
Hi @vnea 
Sorry for the delay! 

This is because `InMemorySigner` will take in either a mnemonic or a secret key and has zero protections to avoid exposure. 

If the class `InMemorySigner` is ever exposed, it can easily be used to find the secret key since its sole purpose is to make Dev life easier for debugging and quick signer use.

Software and Hardware wallets are designed to protect the users' secrets and not be exposable in an application. Usually, it points to a third party, an extension, browser or hardware wallet prompt, that would strictly receive the bytes that want to be signed and return the signature. 

They only allow for the exposure of a signature for the bytes to be signed and a public key / public key hash. (there may be more, but they should only be values that are acceptable to be shared)

The Mnemonic is not exposed in the InMemorySigner, but it is possible for the secret key of the derivation path to be used from the mnemonic -> private key. 

Secret keys should never be held in memory in a vulnerable state and ideally should not even travel encoded over the internet. Some workarounds and fail-safes are used to ease the users' life, but always with risk management to ensure no breaches in the users' vulnerable data.

Many wallet providers provide needed security that `InMemorySigner` has omitted for developmental purposes. 

I hope this helps! Please don't hesitate if you have any more questions.

**Comment by vnea** [comment]
Your answer is clear.

Thank you.
