### ISSUE TITLE
[TZIP-012] Fail to parse Token Metadata located in tezos-storage URI

### ISSUE THREAD

**Issue by pewulfman** [ecadlabs/taquito#2120]
**Description**
As a core developer at LigoLang, I have been extending our FA contracts in the database to include token_metadata.
The implementation is there : https://github.com/pewulfman/Tezos-TZIP-implementation/blob/main/TZIP-12%20(FA2)/standard_contract/FA2_multi_asset.mligo#L113
And the contract was published on ghostnet at address KT1FzbvvG8Y6GE4VU7iyGqT7M5TLWzKkDC5X
I experimented with both possibility  for metadata as defined in TZIP-012 : https://github.com/pewulfman/Tezos-TZIP-implementation/blob/main/TZIP-12%20(FA2)/standard_contract/FA2_multi_asset.mligo#L113
I believe the metadata are written correctly and are parsed by both Better-call.dev and TzKT.io

The alternative using a direct map ["name";"symbol";"decimals"] works well. (Token 1 and 3). 
However when using `c.tzip12().getTokenMetadata(0)` taquito returns `The URI { "name" : "Wulfy FA2 multi asset 0", "symbol" : "WMA0", "decimal" : "3", } is present in the token metadata, but is invalid.` or `Uncaught (in promise) InvalidTokenMetadata: Non-compliance with the TZIP-012 standard. The required property `decimals` is missing.`

Looking at the logs. It seem that taquito does resolve the URL, convert from bytes to string. And tries to access the field "decimals" on the strings. I believe it should first parse the string to JSON before trying to access any fields

**Steps To Reproduce**
Fetch contract on `ghostnet` at address : KT1FzbvvG8Y6GE4VU7iyGqT7M5TLWzKkDC5X
```
const c = Tezos.contract.at("KT1FzbvvG8Y6GE4VU7iyGqT7M5TLWzKkDC5X")
c.tzip12().getTokenMetadata(0)
```

**Expected behavior**
The function is supposed to parse the metadata at `tezos-storage:data`, and not fails

**Screenshots**
Success for token_id 1 :
![image (1)](https://user-images.githubusercontent.com/24414913/201900315-3b7593bb-923d-433e-b010-16863eb58526.png)

Some info on what is parse for token_id 0:
![image (2)](https://user-images.githubusercontent.com/24414913/201900311-cdecc5e5-cbc5-4cc9-b6f2-ad3567c5bc8c.png)
![image (3)](https://user-images.githubusercontent.com/24414913/201900304-4ab15212-8431-4f41-a4fb-1e3572f91515.png)
![image (4)](https://user-images.githubusercontent.com/24414913/201900295-46744d69-3e56-4428-ba7e-cdaed2947376.png)

**Desktop (please complete the following information):**
 - OS: Archlinux

**Additional context**
My collegue posted here : https://github.com/ecadlabs/taquito/issues/503#issuecomment-1315104552

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2120?planning-poker) with Zenhub @hui-an-yang @roxaneletourneau @zainen

**Comment by dsawali** [comment]
Hello @pewulfman, thanks for writing this ticket. I look a bit further into your contract at `KT1FzbvvG8Y6GE4VU7iyGqT7M5TLWzKkDC5X`.

And I found a few things that explain why parsing failed in Taquito. Taquito follows the Tzip12 format as stated here https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-12/tzip-12.md#token-metadata. 

It expects an object of this form:
```
{
  name: "",
  symbol: "",
  decimals: "",
}
```

The issue where you are receiving, as you have already stated above, is due to Taquito not being able to find the `decimals` key in your object (specifically Token 0 and 2).

And looking into the contract in tzkt, Token 0 metadata looks like this:
![image](https://user-images.githubusercontent.com/16856119/206797301-17f1d1f9-a524-40fe-bc2e-b138748c96f0.png)

While we can physically see the Tzip12 metadata format correctly nested inside `data` it's not expected for Taquito to receive extended forms of the metadata, or do any parsing for non-standard forms of it. The correct example of metadata would be in the direct map as you have written for Token 1 and 3.

Having said that, I don't think we can support the format you are using. While it is reasonable request, we would like to keep Taquito to be as in-line and compliant with `Tzip12`. Please let us know if you have any other concerns.

**Comment by Innkst** [comment]
We have suggested an approach that Taquito supports and that is compliant with tzip-12. Closing
