### ISSUE TITLE
Installation and integration test instructions broken?

### ISSUE THREAD

**Issue by arvidj** [ecadlabs/taquito#2134]
**Description**

I'm think I'm doing something wrong, that the Taquito README is not up to date or that something is broken in Taquito :( 

**Steps To Reproduce**

Locally, I've followed the instructions at https://github.com/ecadlabs/taquito#contributors-getting-started
I've installed a pretty fresh node and npm with nvm:

```
$ node --version
v16.18.1

$ npm --version
8.19.2
```

(i've manually removed the folder `node_modules` and uninstalled all
globally installed packages to get something looking like a fresh
install).

Then the instructions mentions running:

 - Run npm clean-install
 - Run npm run rebuild

I think this is an error since `rebuild` seems to also run
`clean-install`, so only the latter or the former should be necessary
. Anyhow, I ran both.

Then I tried `npm run test`. It starts the tests, but there are
errors, for instance:

```
        FAIL  test/taquito-contracts-library.spec.ts
         ● Test suite failed to run
       
           Cannot find module '@taquito/utils' from 'src/taquito-contracts-library.ts'
       
           Require stack:
             src/taquito-contracts-library.ts
             test/taquito-contracts-library.spec.ts
```

I try running the integration tests as per [the instructions](https://github.com/ecadlabs/taquito#running-integration-tests):

```
cd integration-tests
npm run test
```

I'm then bombarded with errors like:

``` 
 FAIL  ./contract-security-on-chain-views.spec.ts
  ● Test suite failed to run

    Cannot find module '@taquito/taquito' from 'contract-security-on-chain-views.spec.ts'

    > 1 | import { Protocols } from '@taquito/taquito';
        | ^
      2 | import { CONFIGS } from './config';
      3 |
      4 | /**   

      at Resolver.resolveModule (../node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (contract-security-on-chain-views.spec.ts:1:1)
```

:( 

**Expected behavior**

Most tests should pass.

**Desktop (please complete the following information):**

Ubuntu 20.04.5 LTS

**Comment by egarson** [comment]
Hi @arvidj,
Thank you for taking the effort to post this.
The README is missing the simple step of `npm run build` at top-level before you do an `npm run test`.
You are also correct that `rebuild` now does a clean, thank you for pointing this out.
We have just added support for external developers to run integration tests against a docker image, so we will also include those instructions when we push the corrected README file. Until recently the integration tests were only able to be run by internal developers because the setup involves using a VPN. So in short, please wait to be able to run the integration tests.
Cheers,
Edward
