### ISSUE TITLE
[Integration Test] Fix ballot operation test to have a dynamic wait

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2403]
`integration-tests/sandbox-ballot-operation.spec.ts` have regressed due to sandboxes now having different block times each protocol. Fix the test so that we can unskip it.

The test relies on block timing as well as waiting the proper amount of time until the voting period changes. Adjust the test to dynamically so that it checks wait times of each protocol and formulate a method to wait correctly.

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2403?planning-poker) with Zenhub @AlirezaHaghshenas @hui-an-yang @zainen

**Comment by stephengaudet** [comment]
"Adjust the test to dynamically so that it checks wait times of each protocol and formulate a method to wait correctly."

Instead of waiting the test could: 
1.poll a RPC endpoint until it finds the condition it is waiting for
2.define a polling frequency
3.define a timeout, after which the test gives up polling rpc and fails the test
