### ISSUE TITLE
[SORU] Add types for remaining Smart Rollup operations not covered in v16

### ISSUE THREAD

**Issue by dsawali** [ecadlabs/taquito#2409]
*As a user, I would like to be able to read any data with smart rollup operations so that I don't get unexpected errors.*

*Background*
Currently, we only have 2-3 smart rollup operations supported in Taquito. However, we'd still like to support reading most all of the other smart rollup operations. 
User applications should work smoothly when reading any operations in the block, even if Taquito encounters smart rollup operations that are not supported in the forger. 

*Acceptance criteria:*
- Add types from the RPC package  for these operations:
- [ ] smart_rollup_publish
- [ ] smart_rollup_cement
- [ ] smart_rollup_recover_bond
- [ ] smart_rollup_refute
- [ ] smart_rollup_timeout
- Unit tests and integration tests are added and successfully pass
- Documentation is updated

context: https://github.com/ecadlabs/taquito/issues/1953

OUT OF SCOPE:
Forging any of the above operations

**Comment by dsawali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Taquito-Development-Team-60ca841c87ca580010057707/issues/ecadlabs/taquito/2409?planning-poker) with Zenhub @AlirezaHaghshenas @hui-an-yang @zainen

**Comment by psmolinsky** [comment]
Hi guys, I noticed that the changes are already released in Taquito 16.1.0. However, there are some glitches - following properties are of type `number` but values from RPC come as `string`-s because in the schema they correspond to `$int64` and `$positive_bignum` which exceed limits of a regular number.
- `SmartRollupPublishCommitment.number_of_ticks`
- `SmartRollupRefutationMove.choice`

**Comment by michaelkernaghan** [comment]
opened https://github.com/ecadlabs/taquito/issues/2440 to capture the comment from psmolinsky
