### ISSUE TITLE
Error: this.walletProvider.mapTransferParamsToWalletParams is not a function

### ISSUE THREAD

**Issue by borderlessdev** [ecadlabs/taquito#2694]
**Description**
I'm getting the following error when i try to make any transaction:
`TypeError: this.walletProvider.mapTransferParamsToWalletParams is not a function`
I know my code works fine because i was using the Temple Wallet from @temple-wallet/dapp and all the functions goes well, but, i moved to the beacon wallet from @airgap/beacon-sdk and starts going this error.
I asked to ChatGPT and says older versions from Taquito won't suport this function (like 9.10 and older), but i'm using the latest one (17.3.1). He also says that @airgap uses the old version: 9.10, but if you set provider of your Tezos instance will be fine, but keeps the same error.
The reason i won't use (at moment) @taquito/beacon-sdk is because my older post mine. I'm using it in Bubble.io, and Bubble kind sucks when you need to import libs.
I don't know if i use @taquito/beacon-wallet will be the solution of my problems because i can't use it.

**Comment by AlirezaHaghshenas** [comment]
Can you please share your code? Or a minimal reproduction?

**Comment by dsawali** [comment]
Hey @borderlessdev,

> I don't know if i use @taquito/beacon-wallet will be the solution of my problems because i can't use it. 

I am fairly certain it will, the method `mapTransferParamsToWalletParams` is exported as part of a member of the `BeaconWallet` class which is from the `taquito-beacon-wallet` package

**Comment by hui-an-yang** [comment]
Hello @borderlessdev 

We're working on a taquito-beacon-wallet bundle that you can use, will keep you posted. 
Will be great to work with you to make sure if the bundle works for your use case with bubble.io.

**Comment by hui-an-yang** [comment]
Hello @borderlessdev 

Would like to reach out to you again I have bundled a taquito-beacon-wallet file, would be great if you could try and see if it works for your use case.
Please can you reach out to me huianyang on [ECAD Labs Discord Channel](https://discord.com/channels/934567382700146739/939205889901092874). That we can collaborate to work out something for you. 
Would also appreciate you could let us know if you already successfully generated a bundle that works so we can close this ticket. 
Thank you

**Comment by oldominion** [comment]
This error is thrown when from a JS environment, you pass in a vanilla dAppClient instance (e.g. from BeaconSDK's getDAppClientInstance() or an instantiated BeaconWallet object's .client property) to Tezos.setWalletProvider() instead of the wrapped client produced from new BeaconWallet().

setWalletProvider() should probably throw an exception if it doesn't receive an object matching the wrapped client instance's interface.

BTW - I have been able to successfully get this working in a Blazor WASM project (which only supports C# interop with JS, not Node\TS), by building a "compiled" taquito-beacon-wallet.js file, roughly as described in https://github.com/ecadlabs/taquito/tree/bundle-taquito-beacon-wallet, and referencing both in <script> tags in my index.html

    <script src="_content/BeaconWalletComponent/taquito.min.js"></script>
    <script src="_content/BeaconWalletComponent/taquito_beacon_wallet.js"></script>
