### ISSUE TITLE
Missing fields in METADATA_BALANCE_UPDATES_CATEGORY in @taquito 19

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#2816]
**Description**
There are some fields missing in `METADATA_BALANCE_UPDATES_CATEGORY` in `@taquito/rpc` despite they are present in Tezos RPC schema for current *Oxford* protocol or previous protocols.

Missing fields from *Oxford* protocol:
- `lost attesting rewards`

Missing fields from older protocols - What is the reason for their removal? Were they not used at all?
- `double signing evidence rewards`
- `fees`
- `legacy_deposits`
- `legacy_fees`
- `legacy_rewards`
- `rewards`

**Comment by hui-an-yang** [comment]
Hello @psmolinsky 
I can't find reference of "lost attesting rewards" in oxford2 open api docs, could you provide where you have came across this info?
`METADATA_BALANCE_UPDATES_CATEGORY ` belongs to an operations response, since people can't get operation response from previous protocol anymore in the reason we keep this enum as updated as current protocol. 
If you have particular use case, will appreciate letting us know what's your use case of keeping the fields from older protocols

**Comment by hui-an-yang** [comment]
hello @psmolinsky,
Hope you're well! We'd like to get your feedback on this ticket before working on next protocol, looking forward to hearing from you. Or we'll have to close it end of 19.2 development. Thank you!
