### ISSUE TITLE
transferTicket function is not implemented for Tezos.wallet 

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taquito#2828]
**Description**
I want to use the transferTicket  function for wallet transactions

![image](https://github.com/ecadlabs/taquito/assets/2536368/af86f614-cd65-4560-ab4f-facad865336c)

It is only availabe for Tezos.contract object ...

![image](https://github.com/ecadlabs/taquito/assets/2536368/0b8f8298-26b6-4127-9025-6ecd9067a692)

I use taquito v19.0.2

**Comment by dsawali** [comment]
Hello @zamrokk, I saw your thread on the dev Slack. You are correct, the `transferTicket` operation is not implemented in the Wallet API. Though this was a conscious decision on our part, we are now re-evaluating and are doing some planning around adding this op (and perhaps other ops) into the Wallet API. 

I'll change the label to `enhancement` instead of `bug` for clarity. Rest assured we will come back to you.

**Comment by zamrokk** [comment]
The function already exist. Is it a big deal just to add it the other object?

Will it be included on the next release?

**Comment by dsawali** [comment]
@zamrokk it requires a lot more organization with the wallet teams as opposed to just adding a member method to the existing wallet class. We don't really have a fixed ETA at the moment.

**Comment by hui-an-yang** [comment]
Hello @zamrokk,  we have added the support of transferTicket in walletAPI in [pr2996](https://github.com/ecadlabs/taquito/issues/2996). This change will be included in next release v21, you can already use it in `v21.0.0-beta.0` therefore closing this ticket
