### ISSUE TITLE
Trying to load an encrypted private key results in an error

### ISSUE THREAD

**Issue by Bladrak** [ecadlabs/taquito#364]
Hi,

I've been trying to load an encrypted private key through the InMemorySigner. Using the taquito boilerplate and taquito version 6.1.0-beta.0 I've got the following error:
```
Uncaught TypeError: _libsodiumWrappers.default.crypto_secretbox_open_easy is not a function
    at decrypt (taquito-signer.ts:57)
    at new Tz1 (ed-key.ts:25)
    at new InMemorySigner (taquito-signer.ts:68)
    at new App (app.ts:13)
    at Object.parcelRequire.main.ts../app (main.ts:3)
    at newRequire (main.c39d6dcf.js:47)
    at main.c39d6dcf.js:81
    at main.c39d6dcf.js:120
```

using the following code:
```.ts
import { Tezos, TezosToolkit } from '@taquito/taquito';
import { InMemorySigner } from '@taquito/signer';
import $ from 'jquery';


const encryptedKey = "...";
const password = "...";

export class App {
  private tk: TezosToolkit = Tezos;

  constructor() {
    this.tk.setProvider({ rpc: 'https://rpc.tezrpc.me', signer: new InMemorySigner(encryptedKey, password) });
  }

 // ...
```

Error is reproduced with Node 12 and 14.

**Comment by jevonearth** [comment]
Hi @Bladrak 

You should try;

`InMemorySigner.fromSecretKey('edsk', 'passphrase')`

instead of:

`InMemorySigner(encryptedKey, password)`

libsodium has to initialise, and we can't do that in the constructor. We provide this static method to get around this. This is noted as a warning in the API's TypeDoc's.

I hope this helps! Closing this for now, but if you need further assistance, please reach out.

**Comment by Bladrak** [comment]
Thanks, seems to be working indeed, but it might be worth updating the documentation here then: https://tezostaquito.io/docs/inmemory_signer#loading-an-encrypted-private-key-with-a-passphrase
