### ISSUE TITLE
Update to latest ledger deps

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#553]
npm packages from `@ledger` need updating, in Taquito, website, tests and examples.

`@ledgerhq/hw-transport-node-hid  ^5.25.0  →  ^5.34.0`

Ledger integration tests need to be run after.

**Comment by Necroskillz** [comment]
While doing this, could you actually remove `@ledgerhq/hw-transport-node-hid` from dependencies? It's not used in the lib code (only in tests/examples) and it complicates build on CI because the package post-install script requires C++/python. Also web apps don't use it at all.

Imo it should only be in `devDependencies` for tests, and consumer should install transport of his choice.

**Comment by andrewpaulicek** [comment]
I think it might also be feasible to move it into peerDependencies
