### ISSUE TITLE
Using Batch API via Wallet API

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#591]
The Batch API is not working when using the Wallet API. Needs investigation, tests written, and documentation written.

**Comment by roxaneletourneau** [comment]
The batch API only works with the contract API. 
A signer needs to be configured to use the batch API because of this line: https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/rpc-estimate-provider.ts#L201

It is possible to batch operations using the batch method of the wallet class.

Example:
```
const batch = await Tezos.wallet.batch([
        { kind: OpKind.TRANSACTION, to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu', amount: 2 },
        { kind: OpKind.TRANSACTION, to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu', amount: 2 },
        { kind: OpKind.TRANSACTION, to: 'tz1ZfrERcALBwmAqwonRXYVQBDT9BjNjBHJu', amount: 2 },
        { kind: OpKind.ORIGINATION, balance: "1", code: ligoSampleMichelson, storage: 0, }
      ]).send();
```

**Comment by roxaneletourneau** [comment]
The `batch` method on the `TezosToolkit` class needs a signer. Thus, it can not be used with a wallet.  
To avoid confusion, this method will be marked as deprecated and moved to the contract API.

There is already a batch method available on the `wallet` class.
