### ISSUE TITLE
Schema.ExtractSchema() returns "list"

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#960]
**Description**

The method [`ExtractSchema()` of `Schema`](https://tezostaquito.io/docs/michelson_encoder/#the-extractschema-method) returns string `"list"` for a complex Michelson starting with a `{ prim: 'list' }`. Or am I wrong and this is an expected exception?

**Steps To Reproduce**
1. Run following code.
    ```typescript
    const storageType = {
        prim: 'list',
        args: [
            {
                prim: 'pair',
                args: [
                    { prim: 'address', annots: ['%from'] },
                    { prim: 'address', annots: ['%to'] },
                ],
            },
        ],
    };
    const storageSchema = new Schema(storageType);
    const extractSchema = storageSchema.ExtractSchema();
    println(JSON.stringify(extractSchema, null, 2));
    ```
2. It prints (returns) string `"list"`.

**Expected behavior**
Expected to return complex object like:
```typescript
[
    {
        "from": "address",
        "to": "address"
    }
]
```

**Comment by roxaneletourneau** [comment]
Thank you for submitting this issue. Indeed, it is much valuable to have information on what compose the list. 
However instead of returning:
```
[
    {
        "from": "address",
        "to": "address"
    }
]
```
we will return an object where the key is 'list' and the value gives information on what compose that list:
```
{
    list: {
        "from": "address",
        "to": "address"
    }
}
```
We chose this approach to be able to distinguish between list and set types. This will be included in version 10.
