### ISSUE TITLE
Custom errors should extend Error

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#973]
Why your custom errors ([1](https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/errors.ts), [2](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-remote-signer/src/errors.ts), [3](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-tzip12/src/tzip12-errors.ts), [4](https://github.com/ecadlabs/taquito/blob/master/packages/taquito-tzip16/src/tzip16-errors.ts), [5](https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/operations/operation-errors.ts)) do not extend `Error` class but only *implements* it?

As a result, currently this check fails (returns `false`) but intuitively it should not: `errorFromTaquito instanceof Error`.

**Comment by roxaneletourneau** [comment]
It is because `instanceof` was not working for custom errors when extending `Error`.
```
class CustomError extends Error {}

const error = new CustomError("custom error");

// prints "true"
console.log(error instanceof Error);
// incorrectly prints "false"
console.log(error instanceof CustomError);
```

**Potential solution:**
As describe [here](https://www.typescriptlang.org/docs/handbook/2/classes.html#inheriting-built-in-types),
a workaround is to manually adjust the prototype immediately after the super(...) calls:
```
class CustomError extends Error {
  constructor(m: string) {
    super(m);
 
    // Set the prototype explicitly.
    Object.setPrototypeOf(this, CustomError.prototype);
  }
}

const error = new CustomError("custom error");
// both print "true" now
console.log(error instanceof Error);
console.log(error instanceof DatabaseError);
```
Note: This workaround will not work on Internet Explorer 10 and prior.
