### ISSUE TITLE
sodium.randombytes_buf is not a function

### ISSUE THREAD

**Issue by vdt000** [ecadlabs/taquito#999]
Hi,
I got an email from airgap, says that: we thank you for your bug message, we deploy new version of wallet-min.js.
And new version working, no "sodium lib bug." Also "\node_modules@airgap\beacon-sdk" has new version 10. BUT still :
"TypeError: sodium.randombytes_buf is not a function
at Object. (\node_modules@airgap\beacon-sdk\dist\cjs\utils\generate-uuid.js:72:34)"
BUG is there.
We use this function:
const wallet = new BeaconWallet({ name: "Beacon Docs Taquito" });
and bug comes.
We must send tez money to our users via nodejs wallet library.
URGENT...

**Comment by claudebarde** [comment]
Is there a way we could get in touch? I'd like to understand better what you are trying to achieve, as I explained to you before, using the `@taquito/beacon-wallet` library in the back-end is generally a bad idea as some libraries will not be supported, that's why we have the `@taquito/signer` library. Please let me know.

**Comment by vdt000** [comment]
Merhaba (Hi),

How can I send Tez money (simple transaction) with @taquito/signer via nose.js? Any code snippet?

Vedat Arslan
Tesekkurler (Thanks) 

    On Wednesday, August 4, 2021, 8:42:46 AM GMT+3, Claude Barde ***@***.***> wrote:  
 
 


Is there a way we could get in touch? I'd like to understand better what you are trying to achieve, as I explained to you before, using the @taquito/beacon-wallet library in the back-end is generally a bad idea as some libraries will not be supported, that's why we have the @taquito/signer library. Please let me know.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by roxaneletourneau** [comment]
Hi @vdt000 

To send an operation using a signer, you will need to use the contract API instead of the wallet API. The first step will be to configure a signer on your TezosToolkit instance (ie [Ledger Signer](https://www.npmjs.com/package/@taquito/ledger-signer), [Remote Signer](https://www.npmjs.com/package/@taquito/remote-signer)). 

Here is an example with a ledger device ([additional documentation](https://tezostaquito.io/docs/ledger_signer)):
```
import { LedgerSigner } from '@taquito/ledger-signer';
import TransportNodeHid from '@ledgerhq/hw-transport-node-hid';
import { TezosToolkit } from '@taquito/taquito';

const Tezos = new TezosToolkit('https://YOUR_PREFERRED_RPC_URL');

const transport = await TransportNodeHid.create();
const ledgerSigner = new LedgerSigner(transport);

Tezos.setProvider({ signer: ledgerSigner });

// To see the public key and the public key hash from the Ledger
const publicKey = await Tezos.signer.publicKey();
const publicKeyHash = await Tezos.signer.publicKeyHash();

// To do the transfer operation
const op = await Tezos.contract.transfer({ to: pkh, amount: x }).send();
await op.confirmation();
```

If this general example does not suit your needs, as @claudebarde suggested, I invite you to book a call with the production team using this [link](https://calendly.com/ecad-product/30-minutes-with-product-team?month=2021-08), so that we can better understand your use case and provide you with a suitable solution.

**Comment by vdt000** [comment]
Merhaba (Hi),

I am very glad for your response.I did exactly as you said.It solves the mystery.Your name Roxane Létourneau?I will ask future questions to you anymore :)

Vedat Arslan
Tesekkurler (Thanks) 

    On Wednesday, August 11, 2021, 9:35:55 PM GMT+3, Roxane Létourneau ***@***.***> wrote:  
 
 


Hi @vdt000

To send an operation using a signer, you will need to use the contract API instead of the wallet API. The first step will be to configure a signer on your TezosToolkit instance (ie Ledger Signer, Remote Signer).

Here is an example with a ledger device (additional documentation):
import { LedgerSigner } from ***@***.***/ledger-signer';
import TransportNodeHid from ***@***.***/hw-transport-node-hid';
import { TezosToolkit } from ***@***.***/taquito';

const Tezos = new TezosToolkit('https://YOUR_PREFERRED_RPC_URL');

const transport = await TransportNodeHid.create();
const ledgerSigner = new LedgerSigner(transport);

Tezos.setProvider({ signer: ledgerSigner });

// To see the public key and the public key hash from the Ledger
const publicKey = await Tezos.signer.publicKey();
const publicKeyHash = await Tezos.signer.publicKeyHash();

// To do the transfer operation
const op = await Tezos.contract.transfer({ to: pkh, amount: x }).send();
await op.confirmation();

If this general example does not suit your needs, as @claudebarde suggested, I invite you to book a call with the production team using this link, so that we can better understand your use case and provide you with a suitable solution.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by roxaneletourneau** [comment]
Glad to know the example worked. I will close this issue. Please feel free if you have any further questions, we invite you to join us on the Taquito Community Support Channel on Telegram https://t.me/tezostaquito.
